name: Java CI with Gradle

# main 브랜치에 push, PR 이벤트 발생시 동작 ..
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # gradlew 파일에 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # Spring Boot 어플리케이션 Build (1)
      - name: Spring Boot Build
        run: ./gradlew clean build --exclude-task test

      # Docker 이미지 Build (2)
      - name: Docker Image Build
        run: docker build -t farmfarm1234/farmfarm-img .

      # DockerHub Login (3)
      - name: Docker Login
        run: echo ${{ secrets.DOCKERHUB_PW }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      # Docker Hub push (4)
      - name: Docker Hub Push
        run: docker push farmfarm1234/farmfarm-img

      # GET GitHub IP (5)
      - name: Get GitHub IP
        id: ip
        uses: haythem/public-ip@v1.2

      # Configure AWS Credentials (6) - AWS 접근 권한 취득(IAM)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # Add GitHub IP to AWS (7)
      - name: Add GitHub IP to AWS
        run: |
          aws ec2 authorize-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32

#      # Upload application.yml to EC2
#      - name: Upload application.yml to EC2
#        uses: appleboy/scp-action@v0.1.0
#        with:
#          source: "src/main/resources/application.yml"
#          target: "ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/config/application.yml"
#          key: ${{ secrets.EC2_KEY }}
#          port: ${{ secrets.EC2_SSH_PORT }}

      # AWS EC2 Server Connect & Docker 명령어 실행 (8)
      - name: AWS EC2 Connection
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          timeout: 60s
          script: |
            sudo docker stop farmfarm-img || true
            sudo docker rm farmfarm-img || true
            sudo docker run -d -p 9000:9000 -v /home/ubuntu/config/application.yml:/app/config/application.yml --name farmfarm-img farmfarm1234/farmfarm-img



      # REMOVE GitHub IP FROM security group (9)
      - name: Remove IP FROM security group
        run: |
          aws ec2 revoke-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32